# Generated by Django 3.2.19 on 2023-11-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0049_auto_20220629_1315'),
        ('EvalData', '0051_auto_20231101_1100'),
    ]

    operations = [
    ]
